repos:
- repo: local
  hooks:
    # ---------- 快速提交前运行 ----------
  - id: gofumpt
    name: gofumpt
    entry: D:/gopath/bin/gofumpt.exe
    language: system
    files: \.go$
    pass_filenames: false    # 使用 stdin/stdout，避免 -w 冲突

  - id: goimports
    name: goimports
    entry: D:/gopath/bin/goimports.exe
    language: system
    files: \.go$
    pass_filenames: false    # 使用 stdin/stdout

  - id: golangci-lint
    name: golangci-lint
    entry: D:/gopath/bin/golangci-lint.exe
    language: system
    pass_filenames: false
    args: ["run", "./..."]

  - id: staticcheck
    name: staticcheck
    entry: D:/gopath/bin/staticcheck.exe
    language: system
    pass_filenames: false
    args: ["./..."]

  - id: misspell
    name: misspell
    entry: D:/gopath/bin/misspell.exe
    language: system
    files: \.go$
    pass_filenames: false
    args: ["-error"]

  # ---------- 慢检查（建议在 push 或 CI 执行） ----------
  - id: gotestsum
    name: gotestsum
    entry: D:/gopath/bin/gotestsum.exe
    language: system
    pass_filenames: false
    args: ["--format","testname","--","-race","-cover","./..."]
    stages: [pre-push]

  - id: gosec
    name: gosec
    entry: D:/gopath/bin/gosec.exe
    language: system
    pass_filenames: false
    args: ["-exclude-dir=vendor","-exclude-dir=testdata","./..."]
    stages: [pre-push]

  - id: govulncheck
    name: govulncheck
    entry: D:/gopath/bin/govulncheck.exe
    language: system
    pass_filenames: false
    args: ["./..."]
    stages: [pre-push]

  - id: go-licenses
    name: go-licenses
    entry: D:/gopath/bin/go-licenses.exe
    language: system
    pass_filenames: false
    args: ["check","./..."]
    stages: [pre-push]
