repos:
- repo: local
  hooks:
    # ---------- 快速提交前运行 ----------
  - id: gofumpt
    name: gofumpt
    entry: gofumpt
    language: system
    files: \.go$
    pass_filenames: true
    args: ["-w"]

  - id: goimports
    name: goimports
    entry: goimports
    language: system
    files: \.go$
    pass_filenames: true
    args: ["-w"]

  - id: golangci-lint
    name: golangci-lint
    entry: golangci-lint
    language: system
    pass_filenames: false
    args: ["run", "./..."]

  - id: staticcheck
    name: staticcheck
    entry: staticcheck
    language: system
    pass_filenames: false
    args: ["./..."]

  - id: misspell
    name: misspell
    entry: misspell
    language: system
    files: \.go$
    pass_filenames: true
    args: ["-error"]

  # ---------- 慢检查（建议在 push 或 CI 执行） ----------
  - id: gotestsum
    name: gotestsum
    entry: gotestsum
    language: system
    pass_filenames: false
    args: ["--format","testname","--","-race","-cover","./..."]
    stages: [pre-push]

  - id: gosec
    name: gosec
    entry: gosec
    language: system
    pass_filenames: false
    args: ["-exclude-dir=vendor","-exclude-dir=testdata","./..."]
    stages: [pre-push]

  - id: govulncheck
    name: govulncheck
    entry: govulncheck
    language: system
    pass_filenames: false
    args: ["./..."]
    stages: [pre-push]

  - id: go-licenses
    name: go-licenses
    entry: bash
    language: system
    pass_filenames: false
    args:
    - -c
    - |
      go-licenses check $(go list -m all | tail -n +2)
    stages: [manual]
